### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by rml9ty** [Xruptor/xanSoundAlerts#1]
Message: Interface\AddOns\xanSoundAlerts\config.lua:188: bad argument #2 to 'format' (string expected, got nil)
Time: Wed Jul  7 23:51:09 2021
Count: 1
Stack: Interface\AddOns\xanSoundAlerts\config.lua:188: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\xanSoundAlerts\config.lua"]:188: in function `EnableConfig'
[string "@Interface\AddOns\xanSoundAlerts\xanSoundAlerts.lua"]:116: in function `EnableAddon'
[string "@Interface\AddOns\xanSoundAlerts\xanSoundAlerts.lua"]:26: in function <Interface\AddOns\xanSoundAlerts\xanSoundAlerts.lua:15>

Locals: (*temporary) = "Enable additional [%s] sound notifications."
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Xruptor** [comment]
Replace the config.lua file with this one in the zip and tell me if that fixes the issue please.

[config.zip](https://github.com/Xruptor/xanSoundAlerts/files/6787343/config.zip)

**Comment by Skyzo-be** [comment]
Hello,
I have no more error with the new config.lua file .

**Comment by Xruptor** [comment]
> Hello,
> I have no more error with the new config.lua file .

Oh good thanks for the confirmation!
